### ISSUE TITLE
"Did not find child GUID [value] in Replication.Configuration"

### ISSUE THREAD

**Issue by per-samuelsson** [Starcounter/Replicator#11]
Have latest nightly: **Version=2.3.588**

Three databases: "root", "child1" (7447ac51-6522-42d4-9df9-124b746d1e3b), "child2" (17311ecd-104d-434d-9692-4ade7d3c85b2). Both childs have been setup to replicate to parent "root".

After I start database "root", I see 2 messages in the Console, saying

> "Did not find child GUID [value] in Replication.Configuration"

One message for each child GUID.

What does that mean? What should I as a user do with this information?

**Comment by linkdata** [comment]
Just means there was no specific configuration information (timeout settings) found for that database. Ignore it.

**Comment by linkdata** [comment]
The debug messages have been removed.
