### ISSUE TITLE
"sink wsID=1152924803141730971 not found"

### ISSUE THREAD

**Issue by per-samuelsson** [Starcounter/Replicator#13]
Same setup as in #11.

On regular intervals, I see the following in the console of the "root" database.

```
sink wsID=1152924803141730971 not found
```

Same thinking as in #11 basically: is it something I should act on? Is it a warning? Is my setup not right?

**Comment by linkdata** [comment]
Probably a delayed callback from the logreader when the websocket has gone away. Hard to tell without callstack. Should be fixed but should not cause corruption or follow-on errors.

**Comment by linkdata** [comment]
I've removed the debug messages as they're no longer needed.
