### ISSUE TITLE
Best design for a default table blacklist?

### ISSUE THREAD

**Issue by per-samuelsson** [Starcounter/Replicator#21]
Once I get a confirmation of [this issue](https://github.com/Starcounter/Starcounter/issues/3328), I planning to introduce some recommended, default blacklist in the replicator (right now, it contains no filtering by default, which is good). Any best spot / design for that?

**Comment by per-samuelsson** [comment]
Bump. I don't understand exactly how filtering is to be implemented any more. There was so much talk about that it should change from being managed by handlers into something else. But was that ever done? I just know that the default changed from replicating nothing to everything.

**Comment by linkdata** [comment]
Blacklists would be horribly error prone, hard to maintain and hard to recover from, as stuff would get replicated and then you'd have to try and figure out what broke, add to the blacklists and rebuild databases hoping for the best.

Replicating everything by default is good only for simple testing, and it seems we're progressing past that now. While the Replicator technically uses whitelists, you can certainly generate those lists programmatically. For instance, a set of regular expressions applied to the list of database classes gotten from metadata tables.

We don't want too much high level functionality inside the Replicator itself, that is best left to more advanced products that build on top of it.

**Comment by per-samuelsson** [comment]
Hmm, well, the problem with whitelisting in Starcounter is that its really really hard to say what *should* get replicated, because there's so many underlying "extras" you can't really grasp as a developer. Without quite mature tooling (like checklists of tables or even table sets, I'd say it's more or less practically impossible at this point). 

As an example, I guess the pretty basic Sweoffshore application would have to replicate 100 tables or so, considering it builds on `Simplified` / `SocietyObjects`. White-listing those one by one by name is not really something I'd like to do.

I'm not saying the approach you suggest is wrong. But it's practically a bit hard right now, considering the relative immaturity of replicator tooling / management.

At the same time, replicating everything is not possible either (x) - once you just start the replicator it will crash because of what I describe in #9 and here: https://github.com/Starcounter/Starcounter/issues/3328.

> While the Replicator technically uses whitelists, you can certainly generate those lists programmatically.

It does? I thought it replicated everything as the new default? Or is the design so that you either replicate everything, *or* need to whitelist everything that should get replicated? If so, could you give me some simple pointer to how I can create a simple white-list to start with, and maybe I can figure out something from that.

*(x) if you use just the standard apps from our prefabs, like `Launcher`*

**Comment by linkdata** [comment]
It expects a Dictionary<string, int> of classes and priorities. If the dictionary is null, everything is replicated. If it's not null, only the classes found in the dictionary gets replicated. Note that it takes a copy of the dictionary, so to change the current ruleset you have to create a new Replicator (this is intentional).

Have a look at https://github.com/Starcounter/Replicator/blob/master/Program.cs#L242

**Comment by per-samuelsson** [comment]
> It expects a Dictionary of classes and priorities. If the dictionary is null, everything is replicated. If it's not null, only the classes found in the dictionary gets replicated.

I see. Thanks. So it's either everything, or nothing + what you accept. Then I know what I have to work with. I'll try to figure something out that works for the particular case.

So what about whats written in the repo overview (ReadMe) and everything here: https://github.com/Starcounter/Replicator/blob/master/ReplicationTests.cs. That's all deprecated now? That was part of what confused me how to get filtering up and running.

> Have a look at https://github.com/Starcounter/Replicator/blob/master/Program.cs#L242

Is that a hint to how you see my relation to reality?!?! :wink: (I think that link was just a bit off, haha)

**Comment by linkdata** [comment]
> Is that a hint to how you see my relation to reality?!?! :wink: (I think that link was just a bit off, haha)

Man, you're just tooo slooow. That link was only good for a few minutes, until I pushed the next version of Program.cs. Next time, I'll make sure to send you a dead-tree copy of the source.

On a more serious note, yeah. The README needs updating. I'll get on that.

**Comment by per-samuelsson** [comment]
Haha, I'm just very old, don't forget that! :older_man: 

> On a more serious note, yeah. The README needs updating. I'll get on that.

Cool. No stress, I just wanted to know I understood the progress correctly. If `ReplicationTests.cs` is obsolete, I'd suggest we drop that one for clarity too.

**Comment by per-samuelsson** [comment]
Just tested this:

1. Create an empty database.
2. Start the replicator (note: no other application, not now, not historically)
3. Iterate the set of classes to consider white-list filtering.

Here's where anyone will need to start with doing that (minus metadata, since #24 indicates they are filtered on the lowest level already):

```
89 classes:
Starcounter.Metadata.DataType, Starcounter.Metadata.DataType, , sccode.exe
Starcounter.Metadata.Member, Starcounter.Metadata.Member, , sccode.exe
Starcounter.Internal.Metadata.SetSpecifier, Starcounter.Internal.Metadata.SetSpecifier, , sccode.exe
Starcounter.Metadata.DbPrimitiveType, Starcounter.Metadata.DbPrimitiveType, , sccode.exe
Starcounter.Metadata.MapPrimitiveType, Starcounter.Metadata.MapPrimitiveType, , sccode.exe
Starcounter.Metadata.RawView, Starcounter.Metadata.RawView, , sccode.exe
Starcounter.Metadata.VMView, Starcounter.Metadata.VMView, , sccode.exe
Starcounter.Metadata.Index, Starcounter.Metadata.Index, , sccode.exe
Starcounter.Internal.Metadata.RawColumn, Starcounter.Internal.Metadata.RawColumn, , sccode.exe
Starcounter.Internal.Metadata.ReferenceRawColumn, Starcounter.Internal.Metadata.ReferenceRawColumn, , sccode.exe
Starcounter.Metadata.ClrClass, Starcounter.Metadata.ClrClass, , sccode.exe
Starcounter.Metadata.Property, Starcounter.Metadata.Property, , sccode.exe
Starcounter.Metadata.CodeProperty, Starcounter.Metadata.CodeProperty, , sccode.exe
Starcounter.Metadata.MappedProperty, Starcounter.Metadata.MappedProperty, , sccode.exe
Simplified.Ring2.ContactInfoRelation, Simplified.Ring2.ContactInfoRelation, Replicator, sccode.exe
Simplified.Ring6.SkypeIdRelation, Simplified.Ring6.SkypeIdRelation, Replicator, sccode.exe
Starcounter.Metadata.IndexedColumn, Starcounter.Metadata.IndexedColumn, , sccode.exe
Simplified.Ring1.Something, Simplified.Ring1.Something, Replicator, sccode.exe
Simplified.Ring1.Relation, Simplified.Ring1.Relation, Replicator, sccode.exe
PlaceBooking.Database.Booker, PlaceBooking.Database.Booker, Replicator, sccode.exe
Replicator.Configuration, Replicator.Configuration, Replicator, sccode.exe
Starcounter.Layout, Starcounter.Layout, Replicator, sccode.exe
Simplified.Ring1.Illustration, Simplified.Ring1.Illustration, Replicator, sccode.exe
Simplified.Ring1.Somebody, Simplified.Ring1.Somebody, Replicator, sccode.exe
Simplified.Ring1.Event, Simplified.Ring1.Event, Replicator, sccode.exe
Simplified.Ring1.EventInfo, Simplified.Ring1.EventInfo, Replicator, sccode.exe
Simplified.Ring1.EventGroup, Simplified.Ring1.EventGroup, Replicator, sccode.exe
Simplified.Ring6.ChatAttachment, Simplified.Ring6.ChatAttachment, Replicator, sccode.exe
Simplified.Ring6.ChatMessage, Simplified.Ring6.ChatMessage, Replicator, sccode.exe
Simplified.Ring6.WebContent, Simplified.Ring6.WebContent, Replicator, sccode.exe
Simplified.Ring6.WebMap, Simplified.Ring6.WebMap, Replicator, sccode.exe
Simplified.Ring6.WebSection, Simplified.Ring6.WebSection, Replicator, sccode.exe
Simplified.Ring6.WebUrl, Simplified.Ring6.WebUrl, Replicator, sccode.exe
Simplified.Ring2.ContactInfo, Simplified.Ring2.ContactInfo, Replicator, sccode.exe
Simplified.Ring6.SkypeId, Simplified.Ring6.SkypeId, Replicator, sccode.exe
Simplified.Ring6.ResetPassword, Simplified.Ring6.ResetPassword, Replicator, sccode.exe
Simplified.Ring6.WebTracker, Simplified.Ring6.WebTracker, Replicator, sccode.exe
Simplified.Ring2.ContactInfoRelationType, Simplified.Ring2.ContactInfoRelationType, Replicator, sccode.exe
Simplified.Ring6.WebRequestHistory, Simplified.Ring6.WebRequestHistory, Replicator, sccode.exe
Simplified.Ring3.SystemUserGroup, Simplified.Ring3.SystemUserGroup, Replicator, sccode.exe
Simplified.Ring5.Package, Simplified.Ring5.Package, Replicator, sccode.exe
Simplified.Ring5.StoreRelation, Simplified.Ring5.StoreRelation, Replicator, sccode.exe
Simplified.Ring5.UriPermission, Simplified.Ring5.UriPermission, Replicator, sccode.exe
Simplified.Ring2.Barcode, Simplified.Ring2.Barcode, Replicator, sccode.exe
Simplified.Ring5.SystemUserSession, Simplified.Ring5.SystemUserSession, Replicator, sccode.exe
Simplified.Ring5.SystemUserTokenKey, Simplified.Ring5.SystemUserTokenKey, Replicator, sccode.exe
Simplified.Ring5.SystemUserUriPermission, Simplified.Ring5.SystemUserUriPermission, Replicator, sccode.exe
Simplified.Ring2.Person, Simplified.Ring2.Person, Replicator, sccode.exe
Simplified.Ring2.Organization, Simplified.Ring2.Organization, Replicator, sccode.exe
Simplified.Ring2.System, Simplified.Ring2.System, Replicator, sccode.exe
Simplified.Ring4.Place, Simplified.Ring4.Place, Replicator, sccode.exe
Simplified.Ring4.PurchaseOrder, Simplified.Ring4.PurchaseOrder, Replicator, sccode.exe
Simplified.Ring3.Product, Simplified.Ring3.Product, Replicator, sccode.exe
Simplified.Ring3.Address, Simplified.Ring3.Address, Replicator, sccode.exe
Simplified.Ring3.GeoLocation, Simplified.Ring3.GeoLocation, Replicator, sccode.exe
Simplified.Ring4.PurchaseOrderItem, Simplified.Ring4.PurchaseOrderItem, Replicator, sccode.exe
Simplified.Ring3.WebAddressRelationType, Simplified.Ring3.WebAddressRelationType, Replicator, sccode.exe
Simplified.Ring3.AddressRelation, Simplified.Ring3.AddressRelation, Replicator, sccode.exe
Simplified.Ring3.AddressRelationType, Simplified.Ring3.AddressRelationType, Replicator, sccode.exe
Simplified.Ring3.EmailAddressRelationType, Simplified.Ring3.EmailAddressRelationType, Replicator, sccode.exe
Simplified.Ring3.PhoneNumberRelation, Simplified.Ring3.PhoneNumberRelation, Replicator, sccode.exe
Simplified.Ring3.EmailAddress, Simplified.Ring3.EmailAddress, Replicator, sccode.exe
Simplified.Ring3.Customer, Simplified.Ring3.Customer, Replicator, sccode.exe
Starcounter.Extensions.DbMapInfo, Starcounter.Extensions.DbMapInfo, Replicator, sccode.exe
Simplified.Ring3.PhoneNumberRelationType, Simplified.Ring3.PhoneNumberRelationType, Replicator, sccode.exe
Simplified.Ring3.SystemUserGroupMember, Simplified.Ring3.SystemUserGroupMember, Replicator, sccode.exe
Starcounter.Extensions.DbMappingRelation, Starcounter.Extensions.DbMappingRelation, Replicator, sccode.exe
Starting replicator in HARBOR. Configured key range: 300000000-399999999
Starcounter.Internal.Metadata.Token, Starcounter.Internal.Metadata.Token, , sccode.exe
Starcounter.Metadata.Table, Starcounter.Metadata.Table, , sccode.exe
Starcounter.Metadata.ClrPrimitiveType, Starcounter.Metadata.ClrPrimitiveType, , sccode.exe
Starcounter.Metadata.Column, Starcounter.Metadata.Column, , sccode.exe
Simplified.Ring1.SomebodiesRelation, Simplified.Ring1.SomebodiesRelation, Replicator, sccode.exe
ReplicationTests.ReplicationTest, ReplicationTests.ReplicationTest, Replicator, sccode.exe
Replicator.Replication, Replicator.Replication, Replicator, sccode.exe
Simplified.Ring1.Content, Simplified.Ring1.Content, Replicator, sccode.exe
Simplified.Ring3.SystemUser, Simplified.Ring3.SystemUser, Replicator, sccode.exe
Simplified.Ring6.ChatGroup, Simplified.Ring6.ChatGroup, Replicator, sccode.exe
Simplified.Ring6.WebTemplate, Simplified.Ring6.WebTemplate, Replicator, sccode.exe
Simplified.Ring1.Type, Simplified.Ring1.Type, Replicator, sccode.exe
Simplified.Ring6.SettingsMailServer, Simplified.Ring6.SettingsMailServer, Replicator, sccode.exe
Simplified.Ring5.Store, Simplified.Ring5.Store, Replicator, sccode.exe
Simplified.Ring5.SystemUserGroupUriPermission, Simplified.Ring5.SystemUserGroupUriPermission, Replicator, sccode.exe
Simplified.Ring2.OrganizationPerson, Simplified.Ring2.OrganizationPerson, Replicator, sccode.exe
Simplified.Ring4.Placement, Simplified.Ring4.Placement, Replicator, sccode.exe
Simplified.Ring3.WebAddress, Simplified.Ring3.WebAddress, Replicator, sccode.exe
Simplified.Ring3.WebAddressRelation, Simplified.Ring3.WebAddressRelation, Replicator, sccode.exe
Simplified.Ring3.EmailAddressRelation, Simplified.Ring3.EmailAddressRelation, Replicator, sccode.exe
Simplified.Ring3.PhoneNumber, Simplified.Ring3.PhoneNumber, Replicator, sccode.exe
Simplified.Ring3.ProductSupplier, Simplified.Ring3.ProductSupplier, Replicator, sccode.exe
```

**Comment by linkdata** [comment]
I'm not sure what you mean.

You select using the full class name with namespace, and the unique set of those after removing the obvious candidates with namespace `Starcounter` gives a set of `Simplified` (which presumably you want to replicate as they look like Society Objects) and `Replicator` which the Replicator itself will prevent if appropriate. And `PlaceBooking`, which I don't know what it is. So it would be one or two `startsWith()` calls, or a one-line regular expression.

The important point to make here is that it's impossible for the Replicator to know what is safe to replicate, and what is not (except it's own tables). And since replicating stuff that should not be replicated is _far_ more dangerous than replicating too little (which is easy to correct), it makes sense to use a whitelist. Deciding what goes on that whitelist is outside the scope of the Replicator itself.

We might make recommendations, especially regarding Society Objects and mapping, but that's best done by those who are developing those technologies.

**Comment by per-samuelsson** [comment]
> I'm not sure what you mean.

Me neither. :wink: 

>  [...] it makes sense to use a whitelist. 

Yeah, guess it does, based on the above reasoning. What I'm trying to illustrate that since we've never *done* this before, it's pretty hard (for anyone) to answer what should get replicated and what should not, in terms of those "built-in" libraries.

> Deciding what goes on that whitelist is outside the scope of the Replicator itself.

Yeah, it should. Eventually, it would be good if we could turn it into that planned configuration-based thing instead though, since it feel like a good thing if we could allow someone to use the replicator without having to maintain a custom build of it, because you need to hard-code the white-list. But I know that was out of the scope of the first version.

> We might make recommendations, especially regarding Society Objects and mapping, but that's best done by those who are developing those technologies.

Yeah, this is one of my main points. It's out of the scope of the replicator, but still need to be done in some context. I'm not sure where. Maybe we should start having every sample / prefab "default" replication setting. Like in a dedicated configuration repository. I don't know. Just rambling. I just know it's practically pretty hard to work with ATM. :smile:

**Comment by linkdata** [comment]
To make the dataset more manageable, try listing only the namespaces:
```
Starcounter
Simplified
Replicator
ReplicationTests
PlaceBooking
```

So let's try to analyze that set.

`ReplicationTests` will get removed, so scratch that. `Replicator` is handled by the Replicator. `Starcounter` is trickier - the log reader filters out system records, but are all `Starcounter` namespaced tables only populated by system records? I have no idea. But until proven needed, why risk replicating it? Same deal for `PlaceBooking`. If you don't know what it is, why replicate it? If it turns out it's needed, you can always add it later and the Replicator will pick it up and transfer it over.

So that leaves `Simplified`. And whichever root namespaces your test applications are using.

**Comment by per-samuelsson** [comment]
> `Starcounter` is trickier - the log reader filters out system records, but are all `Starcounter` namespaced tables only populated by system records? I have no idea.

Me neither. And regarding those, this one relates: https://github.com/Starcounter/Starcounter/issues/3328

**Comment by per-samuelsson** [comment]
> To make the dataset more manageable, try listing only the namespace.

Yeah, that's what I'm about to do, in that new custom replicator. I couldn't see no other way that was better either, and I need something to start with. I think/hope it will work out OK for now.

**Comment by linkdata** [comment]
I got curious to see what `PlaceBooking.Database.Booker` actually was, and I found this:
https://github.com/StarcounterSamples/Simplified/blob/master/Ring6/Booker.cs
@andwah Is there a strong reason to not have this in the `Simplified` namespace?

**Comment by per-samuelsson** [comment]
> @andwah Is there a strong reason to not have this in the Simplified namespace?

Now I'm just going CRAZY guessing, but I bet... well, my pride on thats not intentional. (Feels safe, since I don't have any).

**Comment by andwah** [comment]
@linkdata, i can not come up with a reason,  It should NOT be in `Simplified,`

**Comment by linkdata** [comment]
The PlaceBooking namespace issue has been reported in the correct repo and the README has been updated to reflect whitelisting, so closing this.
