### ISSUE TITLE
Bogus reference to Starcounter.TransactionLog

### ISSUE THREAD

**Issue by per-samuelsson** [Starcounter/Replicator#22]
I'm unable to build a custom replicator based on this repo. Building the solution fail because the reference to `Starcounter.TransactionLog.dll` can not be resolved. 

Looking at [Replicator.csproj](https://github.com/Starcounter/Replicator/blob/master/Replicator.csproj#L46-L48), I see the reference is set up like this:

```xml
<Reference Include="Starcounter.TransactionLog">
  <HintPath>..\..\Program Files\Starcounter\Starcounter.TransactionLog.dll</HintPath>
</Reference>
```

That seems very specific to a certain environment, and also not copying with how other references to Starcounter assemblies are handled.

**Comment by linkdata** [comment]
Yeah, that's a hack. The TransactionLog assembly isn't exposed like the other public Starcounter assemblies. Perhaps @bigwad can make it publicly available?

**Comment by bigwad** [comment]
What do you mean? What does make other assemblies more "publicly available" than TransactionLog?

**Comment by linkdata** [comment]
In the `.csproj` files for Starcounter applications, the standard SC assemblies are referenced like this:
```
    <Reference Include="Starcounter.Logging, Version=2.0.0.0, Culture=neutral, PublicKeyToken=d2df1e81d0ca3abf">
      <Private>False</Private>
    </Reference>
```
However, if I add a reference to TransactionLog the same way,

```
    <Reference Include="Starcounter.TransactionLog, Version=2.0.0.0, Culture=neutral, PublicKeyToken=d2df1e81d0ca3abf">
      <Private>False</Private>
    </Reference>
```

I get this error:
`1>C:\Program Files (x86)\MSBuild\14.0\bin\Microsoft.Common.CurrentVersion.targets(1819,5): warning MSB3245: Could not resolve this reference. Could not locate the assembly "Starcounter.TransactionLog, Version=2.0.0.0, Culture=neutral, PublicKeyToken=d2df1e81d0ca3abf". Check to make sure the assembly exists on disk. If this reference is required by your code, you may get compilation errors.`

I don't know what makes the other assemblies work differently. Perhaps it is related to the installer? Do @alemoi have any insights on this?

**Comment by per-samuelsson** [comment]
> What do you mean? What does make other assemblies more "publicly available" than TransactionLog?

There's a mechanism in the build system, that those assemblies that are to be considered "public" to reference must end up duplicated in a certain folder, %StarcounterBin%\Public Assemblies. I'm not totally sure how that's done, but should be able to search for it. Probably in CopyDependenciesLocal.csproj or something like that.

> I don't know what makes the other assemblies work differently. Perhaps it is related to the installer? Do @alemoi have any insights on this?

See above comment.

**Comment by bigwad** [comment]
Have you tried to add reference using visual studio wizard?

**Comment by bigwad** [comment]
ok, I see. Neither setup nor build copies this assembly into "Public assemblies". I'll investigate.

**Comment by linkdata** [comment]
I've pushed a workaround for this for now, but we should definitely use the pubkey once this is signed and published.

```
    <Reference Include="Starcounter.TransactionLog">
      <HintPath>$(StarcounterBin)\Starcounter.TransactionLog.dll</HintPath>    
      <Private>False</Private>
    </Reference>
```

**Comment by per-samuelsson** [comment]
> I'll investigate.

Great. Make sure it doesn't get copied to the output directory of the referencing project by default too. The same goes for the others, so hopefully you'll find something you can just copy-paste. :smile:

**Comment by bigwad** [comment]
Pushed to level1. Should be available in visual studio reference manager.

**Comment by linkdata** [comment]
`Starcounter.TransactionLog.dll` longer needs the `<HintPath>`, so closing.
