### ISSUE TITLE
Building latest version fail: error CS0117: 'Session' does not contain a definition for 'ForAll'

### ISSUE THREAD

**Issue by per-samuelsson** [Starcounter/Replicator#23]
I'm on the latest commit: https://github.com/Starcounter/Replicator/commit/4383cb9b92efeda647fab14974980308d7661043. I've pulled and built the latest **pnext**; thats on https://github.com/Starcounter/Starcounter/commit/16fce5c517990f8a31edb1d0b8291ce845a5c8b6.

Building the replicator solution gives me

```
error CS0117: 'Session' does not contain a definition for 'ForAll'
```

**Comment by linkdata** [comment]
This is only used to push status updates, so as a workaround you can simply comment it out until the parent issue has a better solution available.

**Comment by per-samuelsson** [comment]
> [...]  as a workaround you can simply comment it out until the parent issue has a better solution available.

OK, I'll try that. Thanks.

**Comment by per-samuelsson** [comment]
Closing this since it's not a build problem anymore, after pulling latest bits.
