### ISSUE TITLE
Implicit filtered tables

### ISSUE THREAD

**Issue by per-samuelsson** [Starcounter/Replicator#24]
There are such, right? Tables the replicator would not replicate out of the box (like replication metadata, for instance).

1. Where can I see that set of tables?
2. If I switch to explicit whitelisting (lex #21), would these tables still be filtered?
3. Do we filter away those tables provided by Starcounter runtime, e.g. `Starcounter.Metadata.*`?

**Comment by bigwad** [comment]
Metadata is filtered out on the lowest level as logreader simply doesn't return it. It's done based on 'system' flag on the record. So no special handling for metadata - any system records are not replicated.
However don't know about any additional filters on replicator level.

**Comment by per-samuelsson** [comment]
> Metadata is filtered out on the lowest level as logreader simply doesn't return it. It's done based on 'system' flag on the record. So no special handling for metadata - any system records are not replicated.

Great. Thanks. Just what I wanted to know. That makes perfect sense.

**Comment by linkdata** [comment]
The replicator filters out it's own tables and records as needed (namespace `Replicator`). It has special handling around those in order to prevent feedback loops.

**Comment by per-samuelsson** [comment]
> The replicator filters out it's own tables and records as needed (namespace `Replicator`). It has special handling around those in order to prevent feedback loops.

Great. Thanks. And since it's now whitelisting once you go custom, they will for sure not end up part of that either, so [2] kind of answers itself (alternatively: [2] was a pretty stupid question). :+1: 

Thanks.
