### ISSUE TITLE
Server log flooded with warnings from Replicator

### ISSUE THREAD

**Issue by per-samuelsson** [Starcounter/Replicator#9]
When running the replicator randomly, i.e. as described in the OP in #7, the server log is flooded with warnings:

![image](https://cloud.githubusercontent.com/assets/2902045/12482684/4ddef382-c051-11e5-81f0-03465e726b0e.png)

As the warning level is to be used to inform the user about something he should immediately address, before it becomes an error, I'm not sure what I should do with the information I'm being given?

It's also hard to see the errors for all the warnings.

**Comment by linkdata** [comment]
This is unrelated to the Replicator. The warnings appear in the log when simply starting a database (no applications necessary). Created https://github.com/Starcounter/Starcounter/issues/3307 and closing this.

**Comment by per-samuelsson** [comment]
> The warnings appear in the log when simply starting a database (no applications necessary).

Ah, sorry. My bad.

> Created Starcounter/Starcounter#3307 and closing this.

Great. Thanks!
